export const AppContent = Object.freeze({
    Introduction: "<b>GUEST APP</b> is a technology solutions aimed to digitize the Philippine Tourism industry.",
    IntroductionBody: "This initiative is aligned with UNWTO\'s focus on innovation, education, digital transformation, and investments. Guest will unify products, services, markets, and the governing bodies in one platform. GUEST App aside from being a productivity tool for travellers serves as a real-time Data Analytics & Promotions Database Repository for LGUs. GUEST aims to be the most reliable and preferred travel app focused on Philippine tourism.",
    Benefits: [
        {
            key: 'Product\nShowcase',
            icon: 'inventory_2',
            color: '#2b70ac',
            description: 'Showcase the destinations, products, and the services in your LGU.'
        },
        {
            key: 'Performance\nTracker',
            icon: 'assignment_turned_in',
            color: '#72be46',
            description: 'Keep track of visitor arrivals and transactions "real-time".'
        },
        {
            key: 'Profit\nSharing',
            icon: 'monitoring',
            color: '#c62e3a',
            description: 'A portion of the profit generated by the LGU will be shared for your future tourism programs.'
        },
        {
            key: 'Private Sector\nPartnerships',
            icon: 'handshake',
            color: '#ef642c',
            description: 'Through the various partnerships that GUEST will forge, you strengthen your relationship with private stakeholders.'
        },
        {
            key: 'Professionalizing\nTravel',
            icon: 'location_on',
            color: '#f7be14',
            description: 'We will professionalize travel planning through content and partnerships, seamless booking, and secure payment platform.'
        }
    ],
    WebDashboardContent: {
        title: 'Web Dashboard for LGU and Merchants',
        features: [
            {
                key: 'Real-Time Analytics',
                description: 'The LGU Dashboard provides real-time data on arrivals, transactions, and customer information specific to your LGU.'
            },
            {
                key: 'Product and Inventory Management',
                description: 'With the Merchant dashboard, our merchant partners can udpate products and services, adjust pricing and manage inventory conveniently.'
            }
        ]
    }
});

export const AppDetails = Object.freeze({
    CompanyName: 'PEPMedia Inc.',
    CopyrightYear: 2023
});
